version: '3.8'

services:
  frontend:
    build:
      args:
        - NODE_ENV=production
    restart: always

  backend-api:
    build:
      args:
        - NODE_ENV=production
    restart: always

  nginx:
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro # Added for SSL in production
    ports:
      - "80:80"
      - "443:443"
